apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-classification-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: image-classification-service
  template:
    metadata:
      labels:
        app: image-classification-service
    spec:
      containers:
        - name: image-classification-service
          image: akshatadocker07/image_classification_service:latest
          ports:
            - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: image-classification-service
spec:
  selector:
    app: image-classification-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: LoadBalancer
