apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-service
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: object-detection-service
  template:
    metadata:
      labels:
        app: object-detection-service
    spec:
      containers:
        - name: object-detection-service
          image: akshatadocker07/object_detection_service:latest  # Docker Hub image
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: object-detection-service
spec:
  selector:
    app: object-detection-service
  ports:
    - protocol: TCP
      port: 80  # External port to access the service
      targetPort: 5002  # Internal port the container listens on
  type: LoadBalancer  # To expose the service outside the cluster
